<?xml version="1.0" encoding="UTF-8"?><testrun name="testeo" project="TP 3 - POO" tests="11" started="11" failures="1" errors="0" ignored="0">
  <testsuite name="test.testeo" time="0.006">
    <testcase name="testLanceroConItems" classname="test.testeo" time="0.0"/>
    <testcase name="testCaballeroConItems" classname="test.testeo" time="0.0"/>
    <testcase name="testAtaquesSoldado" classname="test.testeo" time="0.001"/>
    <testcase name="testArquero" classname="test.testeo" time="0.0"/>
    <testcase name="testCaballero" classname="test.testeo" time="0.0"/>
    <testcase name="testSoldadoConItems" classname="test.testeo" time="0.0"/>
    <testcase name="testLancero" classname="test.testeo" time="0.0"/>
    <testcase name="testAtaquesSoldadoConItems" classname="test.testeo" time="0.003">
      <failure>java.lang.AssertionError: expected:&lt;190.0&gt; but was:&lt;160.0&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:553)&#13;
	at org.junit.Assert.assertEquals(Assert.java:683)&#13;
	at test.testeo.testAtaquesSoldadoConItems(testeo.java:255)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testArqueroConItems" classname="test.testeo" time="0.0"/>
    <testcase name="testAtaquesPorDistancia" classname="test.testeo" time="0.001"/>
    <testcase name="testSoldado" classname="test.testeo" time="0.0"/>
  </testsuite>
</testrun>
